// Fleqi workspace, adapted from shadcn/ui sidebar-07.
import { ChevronsUpDown, ChevronRight, FolderClosed, History, Home, Terminal } from 'lucide-react';
import { Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupContent,SidebarGroupLabel,SidebarHeader,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarRail } from './ui/sidebar';
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator,DropdownMenuTrigger } from './ui/dropdown-menu';
import { Avatar,AvatarFallback } from './ui/avatar';
import { AccentIcon,AssetIcon,SettingsIcon } from '../icons';
import { GithubAccount } from '../Account';
import type { FleqiController } from '../backend';
export function AppSidebar({controller:c}:{controller:FleqiController}) {
  const d=c.snapshot;const profile=d?.profiles.find(p=>p.id===d.settings.defaultProfileId);const account=d?.github?.account??null;
  return <Sidebar variant="inset" collapsible="icon"><SidebarHeader className="titlebar-inset" data-tauri-drag-region><SidebarMenu><SidebarMenuItem><SidebarMenuButton size="lg" onClick={()=>c.navigate('overview')} tooltip="Fleqi 概览"><img src="/app-icon.png" alt="" className="size-8 shrink-0 rounded-lg"/><div className="grid flex-1 text-left text-sm leading-tight"><span className="font-semibold">Fleqi</span><span className="truncate text-xs text-muted-foreground">文件快捷助手</span></div></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarHeader>
    <SidebarContent><SidebarGroup><SidebarGroupLabel>工作区</SidebarGroupLabel><SidebarGroupContent><nav aria-label="应用导航"><SidebarMenu>{([['overview','概览',Home],['tasks','任务记录',History],['library','文件能力',FolderClosed]] as const).map(([id,name,Icon])=><SidebarMenuItem key={id as string}><SidebarMenuButton tooltip={name as string} isActive={c.page===id} aria-current={c.page===id?'page':undefined} onClick={()=>c.navigate(id as string)}><Icon/><span>{name as string}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></nav></SidebarGroupContent></SidebarGroup>
      <SidebarGroup><SidebarGroupLabel>连接与工具</SidebarGroupLabel><SidebarMenu>{([['models','模型与账号','customLink'],['permissions','权限与自检','shield'],['about','关于与更新','infoCircle']] as const).map(([id,name,glyph])=><SidebarMenuItem key={id as string}><SidebarMenuButton tooltip={name as string} onClick={()=>void c.openSettings(id as string)}><AccentIcon name={glyph as never} size={16}/><span>{name as string}</span><ChevronRight className="ml-auto"/></SidebarMenuButton></SidebarMenuItem>)}<SidebarMenuItem><SidebarMenuButton tooltip="侧边终端 · P1 后续提供" disabled><Terminal/><span>侧边终端</span><span className="ml-auto text-[10px] text-muted-foreground">P1</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup>
    </SidebarContent><SidebarFooter><SidebarMenu><SidebarMenuItem><DropdownMenu><DropdownMenuTrigger asChild><SidebarMenuButton size="lg" tooltip="账号与工作区"><Avatar className="size-8 rounded-lg">{account?.avatarUrl?<img src={account.avatarUrl} alt=""/>:<AvatarFallback className="rounded-lg bg-muted text-xs">{account?.login?account.login.slice(0,2).toUpperCase():'FQ'}</AvatarFallback>}</Avatar><div className="grid flex-1 text-left text-sm leading-tight"><span className="truncate font-medium">{account?.name||account?.login||'未登录'}</span><span className="truncate text-xs text-muted-foreground">{account?.loggedIn?'已通过 GitHub 登录':'通过 GitHub 登录'}</span></div><ChevronsUpDown className="ml-auto size-4"/></SidebarMenuButton></DropdownMenuTrigger><DropdownMenuContent className="min-w-64" side="right" align="end" sideOffset={8}><DropdownMenuLabel className="py-2">GitHub 账号<p className="mt-1 text-xs font-normal text-muted-foreground">{account?.loggedIn?`${account.login} · 已登录`:'登录后即可同步团队与更新通道'}</p></DropdownMenuLabel><DropdownMenuSeparator/><div className="px-2 py-2"><GithubAccount controller={c} compact/></div><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>void c.openSettings('models')}><AssetIcon name="customLink" size={15}/>模型与账号{profile?.name?<span className="ml-auto text-xs text-muted-foreground">{profile.name}</span>:null}</DropdownMenuItem><DropdownMenuItem onSelect={()=>void c.openSettings('about')}><AssetIcon name="infoCircle" size={15}/>关于与更新</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton tooltip="设置" onClick={()=>void c.openSettings('general')}><SettingsIcon/><span>设置</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter><SidebarRail/>
  </Sidebar>;
}
