import { AutoHeight,AnimatePresence,motion,Reveal } from './motion';
import { useEffect,useRef,useState } from 'react';
import { Check, ExternalLink, Keyboard, Terminal } from 'lucide-react';
import { Button } from './components/ui/button';
import { Badge } from './components/ui/badge';
import { Card } from './components/ui/card';
import { Switch } from './components/ui/switch';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from './components/ui/dialog';
import { ActionButton,Choice,EmptyState,SettingRow,SettingsGroup } from './ui';
import { backend,statusLabels,type FleqiController,type TaskRecord } from './backend';
import { getMaterialSupport,type MaterialSupport } from './native';
import { GithubAccount } from './Account';
import { ACCENT,ACCENT_DARK,AccentIcon,AssetIcon,PiIcon,SettingsIcon,TintIcon,type GlyphName } from './icons';
export function shortcutLabel(value:string){return value.replaceAll('Control','⌃').replaceAll('Alt','⌥').replaceAll('Super','⌘').replaceAll('Shift','⇧').replaceAll('Space','空格').replaceAll('+',' ');}
function ShortcutRecorder({controller:c}:{controller:FleqiController}) {
  const saved=c.snapshot!.settings.shortcut;const [recording,setRecording]=useState(false);const [candidate,setCandidate]=useState(saved);const [hint,setHint]=useState('');const field=useRef<HTMLButtonElement>(null);const capturing=useRef(false);
  useEffect(()=>setCandidate(saved),[saved]);
  const stop=async()=>{capturing.current=false;setRecording(false);try{await backend('shortcut_record',{recording:false});}catch(e){c.setNotice(String(e));}};
  useEffect(()=>{const blur=()=>{if(capturing.current)void stop();};window.addEventListener('blur',blur);return()=>{window.removeEventListener('blur',blur);if(capturing.current)void backend('shortcut_record',{recording:false}).catch(()=>{});};},[]);
  return <div className="space-y-2"><div className="flex items-center justify-end gap-2"><Button ref={field} variant="outline" className="min-w-44 tabular-nums" aria-label="录入底部栏快捷键" aria-pressed={recording} onClick={async()=>{try{await backend('shortcut_record',{recording:true});capturing.current=true;setRecording(true);setHint('按下组合键；Esc 取消');field.current?.focus();}catch(e){c.setNotice(String(e));}}} onBlur={()=>{if(capturing.current)void stop();}} onKeyDown={e=>{
    if(!capturing.current)return;e.preventDefault();e.stopPropagation();if(e.key==='Escape'){void stop();setHint('已取消录入');return;}
    if(['Control','Alt','Shift','Meta'].includes(e.key))return;
    if(e.nativeEvent.isComposing||(!e.ctrlKey&&!e.altKey&&!e.metaKey)){setHint('请至少包含 Control、Option 或 Command');return;}
    const code=e.code;const key=code==='Space'?'Space':/^Key[A-Z]$/.test(code)?code.slice(3):/^Digit[0-9]$/.test(code)?code.slice(5):/^F\d{1,2}$/.test(code)?code:({ArrowUp:'Up',ArrowDown:'Down',ArrowLeft:'Left',ArrowRight:'Right',Enter:'Enter',Backspace:'Backspace'} as Record<string,string>)[code];
    if(!key){setHint('此按键暂不支持，请选择字母、数字、空格或功能键');return;}
    setCandidate([e.ctrlKey&&'Control',e.altKey&&'Alt',e.shiftKey&&'Shift',e.metaKey&&'Super',key].filter(Boolean).join('+'));setHint('点击保存，立即检查快捷键是否可用');void stop();
  }}><Keyboard size={15}/>{recording?'请按下快捷键…':shortcutLabel(candidate)}</Button><ActionButton variant="outline" size="sm" disabled={recording||candidate===saved} action={async()=>{if(await c.save({shortcut:candidate}))setHint('快捷键已更新');}}>保存</ActionButton></div><p className="text-right text-xs text-muted-foreground" role="status">{hint||'点击录入，然后按下你要使用的组合键'}</p></div>;
}
export function General({controller:c}:{controller:FleqiController}) {const d=c.snapshot!,s=d.settings;return <div className="space-y-6"><SettingsGroup><SettingRow title="登录时启动" description="登录后驻留菜单栏。"><Switch aria-label="登录时启动" checked={s.launchAtLogin} disabled={!d.native} onCheckedChange={v=>void c.save({launchAtLogin:v})}/></SettingRow><SettingRow title="启用底部快捷栏" description="使用菜单栏或快捷键唤起。"><Switch aria-label="启用底部快捷栏" checked={s.barEnabled} onCheckedChange={v=>void c.save({barEnabled:v})}/></SettingRow><SettingRow title="唤起方式" description="移动 Finder 时隐藏，放下后重新显示。"><Choice label="唤起方式" value={s.activation} onChange={v=>void c.save({activation:v as 'manual'|'automatic'})} options={[{value:'manual',label:'仅手动唤起'},{value:'automatic',label:'随 Finder 自动显示'}]}/></SettingRow></SettingsGroup><SettingsGroup title="任务回复气泡"><SettingRow title="显示方式" description={s.bubbleSeconds===null?'气泡常驻，右侧带关闭按钮。':`任务结束后气泡显示 ${s.bubbleSeconds.toFixed(1)} 秒后自动消失。`}><Choice label="显示方式" value={s.bubbleSeconds===null?'pinned':'timed'} onChange={v=>void c.save({bubbleSeconds:v==='pinned'?null:6.0})} options={[{value:'timed',label:'自动消失'},{value:'pinned',label:'常驻显示'}]}/></SettingRow>{s.bubbleSeconds!==null&&<div className="px-5 pb-5"><div className="flex items-center justify-between text-xs"><label htmlFor="bubble-seconds">消失倒计时</label><span className="text-muted-foreground">{s.bubbleSeconds.toFixed(1)} 秒</span></div><input id="bubble-seconds" type="range" min={1} max={30} step={0.1} value={s.bubbleSeconds} aria-label="气泡消失秒数" className="bubble-slider mt-3 w-full" onChange={e=>void c.save({bubbleSeconds:Number(e.target.value)})}/><p className="mt-2 text-xs text-muted-foreground">1–30 秒，无级调节。</p></div>}</SettingsGroup><SettingsGroup title="快捷键"><div className="p-5"><h3 className="mb-4 text-sm font-medium">显示 / 收起底部栏</h3><ShortcutRecorder controller={c}/></div></SettingsGroup><p className="text-xs leading-6 text-muted-foreground">关闭窗口后，Fleqi 继续驻留菜单栏。使用菜单中的“退出 Fleqi”结束应用。</p></div>;}
export function AppearanceSettings({controller:c}:{controller:FleqiController}) {
  const s=c.snapshot!.settings;const [support,setSupport]=useState<MaterialSupport>({native:false,liquid:false,reduceTransparency:false});useEffect(()=>{void getMaterialSupport().then(setSupport).catch(()=>{});},[]);
  return <div className="space-y-6"><section><h2 className="mb-3 text-sm font-medium">颜色</h2><div className="grid grid-cols-2 gap-4">{(['light','dark'] as const).map(theme=><button key={theme} className={`appearance-option ${s.appearance.theme===theme?'selected':''}`} aria-label={theme==='light'?'浅色':'黑色'} aria-pressed={s.appearance.theme===theme} onClick={()=>void c.save({appearance:{theme}})}><span className={`appearance-mini ${theme}`}><span>+</span><i/><AssetIcon name="send" size={14}/><SettingsIcon width={17}/></span><span className="mt-3 flex items-center justify-between text-xs">{theme==='light'?'浅色':'黑色'}{s.appearance.theme===theme&&<Check size={14}/>}</span></button>)}</div><p className="mt-3 text-xs text-muted-foreground">浅色与黑色使用相同的尺寸、间距与圆角。</p></section><SettingsGroup title="玻璃材质"><SettingRow title="磨砂玻璃" description="柔和透光，默认材质。"><input type="radio" name="material" aria-label="磨砂玻璃" checked={s.appearance.material==='frosted'} onChange={()=>void c.save({appearance:{material:'frosted'}})}/></SettingRow><SettingRow title="液态玻璃" description={support.liquid?'使用 macOS 原生玻璃材质。':'需要 macOS 26+ 原生应用。'}><input type="radio" name="material" aria-label="液态玻璃" checked={s.appearance.material==='liquid'} disabled={!support.liquid} onChange={()=>void c.save({appearance:{material:'liquid'}})}/></SettingRow></SettingsGroup>{support.reduceTransparency&&<p className="text-xs text-muted-foreground">已遵循系统“减少透明度”设置。</p>}</div>;
}
// 权限与状态配色统一到应用强调色（蓝 / 白 / 黑），只有异常状态用暖色提醒。
const permissionGlyphs:Record<string,[GlyphName,string,string]>={
  accessibility:['accessibility',ACCENT,ACCENT_DARK],
  automation:['pointer',ACCENT,ACCENT_DARK],
  files:['folder',ACCENT,ACCENT_DARK],
  full_disk:['internalDriveFill',ACCENT,ACCENT_DARK],
};
// 徽章内的状态小图标：已授权用强调蓝，异常状态才用暖色。
const statusGlyphs:Record<string,[GlyphName,string,string]>={
  granted:['checkmarkCircleFill',ACCENT,ACCENT_DARK],
  partial:['exclamationTriangle','#D97706','#F0A63C'],
  unknown:['shieldExclamation','#8A94A6','#9AA5B5'],
  not_granted:['shieldSlash','#D4453C','#FF6B61'],
  unsupported:['infoCircle','#8A94A6','#9AA5B5'],
};
function StatusBadge({status}:{status:string}) {
  const label=status==='granted'?'系统已授权':status==='partial'?'部分授权':status==='unknown'?'待验证':status==='unsupported'?'尚未支持':'未授权';
  const glyph=statusGlyphs[status]??statusGlyphs.unknown;
  return <Badge variant="secondary" className="status-badge"><TintIcon name={glyph[0]} size={13} light={glyph[1]} dark={glyph[2]}/>{label}</Badge>;
}
export function Permissions({controller:c}:{controller:FleqiController}) {const d=c.snapshot!;return <div className="space-y-6"><div className="flex justify-between"><h2 className="text-sm font-medium">系统权限</h2><ActionButton size="sm" variant="outline" action={()=>c.run('permissions_check',undefined,'权限检查完成')}><AssetIcon name="clockRotate" size={14}/>重新检查</ActionButton></div><SettingsGroup>{d.permissions.length?d.permissions.map(p=><SettingRow key={p.id} glyph={permissionGlyphs[p.id]&&<TintIcon name={permissionGlyphs[p.id][0]} light={permissionGlyphs[p.id][1]} dark={permissionGlyphs[p.id][2]}/>} title={p.name} description={`${p.purpose}。${p.detail}`}><div className="flex flex-col items-end gap-2"><StatusBadge status={p.status}/><ActionButton size="sm" variant="outline" disabled={!d.native||p.status==='unsupported'} action={()=>c.run('permissions_request',{id:p.id})}>{p.status==='granted'?'查看 / 检查':'前往授权'}</ActionButton></div></SettingRow>):<EmptyState icon={<TintIcon name="shield" size={28} light="#64748B" dark="#9AA5B5"/>} title="在 Fleqi 中检查权限" description="浏览器无法查询此 Mac 的系统权限。"/>}</SettingsGroup><SettingsGroup title="实际检查"><SettingRow title="Finder 窗口与选区" description="读取实际文件窗口的目录和所选文件。"><ActionButton variant="outline" size="sm" disabled={!d.native} action={()=>c.run('context_capture',undefined,'Finder 上下文检查通过')}>检查 Finder</ActionButton></SettingRow><Reveal show={!!d.context}>{d.context&&<div className="break-all bg-muted/50 px-5 pb-4 pt-3 text-xs leading-6">{d.context.directory}<p className="text-muted-foreground">{d.context.files.length?`已获取 ${d.context.files.length} 个文件对象`:'未读到选中的文件：请在 Finder 窗口内选中后重试（文件选择对话框中的选中不会被读取）'} · {new Date(d.context.capturedAt).toLocaleTimeString()}</p></div>}</Reveal><SettingRow title="内置 PI 文件自检" description={d.settings.defaultProfileId?'选择测试位置，执行新建、读取、改名和清理。':'自检通过模型执行真实文件操作，请先在“模型与账号”设置默认连接。'}><ActionButton variant="outline" size="sm" disabled={!d.native||!d.settings.defaultProfileId||!!d.activeTaskId} action={()=>c.run('selftest_start')}>选择位置并自检</ActionButton></SettingRow></SettingsGroup></div>;}
export const fileCapabilities=[['文件与文件夹','新建、复制、移动、改名、批量编号、整理、回收站'],['ZIP','打包、列出内容、解压普通 ZIP'],['图片','PNG / JPG / WebP 转换、缩放、旋转与 JPG 压缩'],['音频与视频','MP3 / M4A / WAV、MP4 转换、音频提取与基础裁剪'],['PDF','普通未加密 PDF 合并、拆分、提页、旋转与结构压缩'],['文本与文档','TXT / Markdown 读取与创建；简单 DOCX 创建与正文提取']];
export function Files({controller:c}:{controller:FleqiController}) {const d=c.snapshot!;const [versions,setVersions]=useState<Record<string,string>|null>(null);return <div className="space-y-6"><SettingsGroup><SettingRow title="默认输出位置" description={d.settings.outputDirectory??'使用当前任务目录，转换保留原件。'}><ActionButton size="sm" variant="outline" disabled={!d.native} action={async()=>{const directory=await c.run<string|null>('choose_directory');if(directory)await c.save({outputDirectory:directory});}}>选择…</ActionButton>{d.settings.outputDirectory&&<ActionButton size="sm" variant="ghost" action={()=>c.save({outputDirectory:null})}>恢复默认</ActionButton>}</SettingRow><SettingRow title="同名文件" description="转换默认保留原件。"><Choice label="同名文件处理" value={d.settings.conflictPolicy} onChange={v=>void c.save({conflictPolicy:v as 'rename'|'ask'})} options={[{value:'rename',label:'生成新名称'},{value:'ask',label:'操作前询问'}]}/></SettingRow></SettingsGroup><div className="flex items-center justify-between"><h2 className="text-sm font-medium">文件引擎</h2><ActionButton variant="outline" size="sm" disabled={!d.native} action={async()=>{const v=await c.run<Record<string,string>>('engines_check');if(v)setVersions(v);}}><AssetIcon name="clockRotate" size={14}/>检查引擎</ActionButton></div><SettingsGroup>{d.engines.length?d.engines.map(e=><SettingRow key={e.id} title={e.name} description={versions?.[e.id]??e.formats}><Badge variant="secondary">{e.ready?'已安装':'未就绪'}</Badge></SettingRow>):<p className="p-5 text-xs text-muted-foreground">引擎状态在原生应用中显示。</p>}</SettingsGroup><SettingsGroup title="文件内容"> <SettingRow title="发送文件内容前确认" description="读取正文并交给模型时，确认本次发送范围。文件名和选区上下文用于理解任务。"/></SettingsGroup></div>;}
export function TaskRow({task,controller:c}:{task:TaskRecord;controller:FleqiController}) {const outputs=[...new Set(task.actions.flatMap(a=>a.result?.outputs??[]))];return <motion.article layout="position" initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}} exit={{opacity:0,height:0,paddingTop:0,paddingBottom:0}} className="task-row"><AutoHeight><div className="flex items-start gap-3"><span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-foreground"/><h3 className="min-w-0 flex-1 truncate text-sm font-medium">{task.prompt}</h3><Badge variant="secondary">{statusLabels[task.status]??task.status}</Badge></div><p className="mt-2 whitespace-pre-wrap break-words text-xs leading-6 text-muted-foreground">{task.message}</p><p className="mt-2 text-[11px] text-muted-foreground">{new Date(task.createdAt).toLocaleString()} · {task.profile.name} · {task.completed} 项操作</p>{outputs.length>0&&<div className="mt-3 flex flex-wrap gap-2">{outputs.map(path=><ActionButton key={path} variant="outline" size="sm" className="max-w-full" action={()=>c.run('result_reveal',{taskId:task.id,path})}><AssetIcon name="folder" size={14}/><span className="truncate">{path.split('/').at(-1)}</span><ExternalLink/></ActionButton>)}</div>}</AutoHeight></motion.article>;}
export function Tasks({controller:c}:{controller:FleqiController}) {const d=c.snapshot!;const [clear,setClear]=useState(false);return <div className="space-y-5"><div className="flex flex-wrap items-center gap-2"><span className="mr-auto text-xs text-muted-foreground">{d.tasks.length} 项任务</span>{d.activeTaskId&&<ActionButton variant="outline" size="sm" action={()=>c.run('task_cancel')}>取消当前任务</ActionButton>}<ActionButton variant="outline" size="sm" disabled={!d.native} action={()=>c.run('diagnostics_export',undefined,'诊断已导出，已移除密钥、正文和私人路径')}>导出诊断</ActionButton><Button variant="ghost" size="icon-sm" aria-label="清理任务历史" disabled={!d.native||!d.tasks.length} onClick={()=>setClear(true)}><AssetIcon name="trash" size={16}/></Button></div><Card className="gap-0 py-0 shadow-none"><AutoHeight><AnimatePresence initial={false}>{d.tasks.length?d.tasks.map(t=><TaskRow key={t.id} task={t} controller={c}/>):<EmptyState icon={<AssetIcon name="clockRotate" size={27}/>} title="还没有任务记录" description="任务完成、失败或取消后，结果会保留在这里。"/>}</AnimatePresence></AutoHeight></Card><p className="text-xs leading-6 text-muted-foreground">异常退出后的未核实动作标为“待核对”。先检查实际产物，再发起新任务。</p><Dialog open={clear} onOpenChange={setClear}><DialogContent><DialogTitle>清理已结束的任务记录？</DialogTitle><DialogDescription>文件和产物会保留，正在运行的任务不受影响。</DialogDescription><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setClear(false)}>取消</Button><ActionButton action={async()=>{await c.run('history_clear');setClear(false);}}>清理记录</ActionButton></div></DialogContent></Dialog></div>;}
export function About({controller:c}:{controller:FleqiController}) {
  const d=c.snapshot!;const account=d.github?.account??null;
  const [checking,setChecking]=useState(false);const [result,setResult]=useState<string|null>(null);
  const check=async()=>{setChecking(true);setResult(null);try{const info=await c.checkUpdate();setResult(info?info.available?`发现新版本 ${info.version}`:'已是最新版本':null);}finally{setChecking(false);}};
  return <div className="space-y-6">
    <div className="about-hero"><span className="about-mark"><img src="/app-icon.png" alt=""/></span><div className="min-w-0 flex-1"><h2 className="about-title">Fleqi</h2><p className="about-subtitle">选中文件，一句话搞定 · {d.runtime.app}</p></div><ActionButton variant="outline" size="sm" disabled={!d.native||checking} action={check}><AssetIcon name="clockRotate" size={14}/>{checking?'正在检查':'检查正式版更新'}</ActionButton></div>
    {result&&<p className="account-hint" role="status">{result}</p>}
    <SettingsGroup>
      <SettingRow title="内置 PI" description="底部任务使用独立的运行环境，随应用一起提供。"><div className="flex items-center gap-2"><PiIcon size={21}/><span className="text-sm">{d.runtime.pi}</span></div></SettingRow>
      <SettingRow title="Node.js" description="运行内置 PI 的独立运行时。"><span className="text-sm">{d.runtime.node}</span></SettingRow>
      <SettingRow title="平台" description={d.platform.detail}><Badge variant="secondary">{d.platform.platform}</Badge></SettingRow>
      <SettingRow title="应用组件" description="Tauri 2 · React · Rust · Swift · shadcn/ui · Border Beam"/>
      <SettingRow title="第三方许可" description="PI 与界面组件、Node.js、FFmpeg、LAME、qpdf 和 libjpeg 的许可随应用资源提供。"/>
    </SettingsGroup>
    <SettingsGroup title="GitHub 与更新通道">
      <SettingRow title="GitHub 账号" description="登录后可用于团队协作、反馈与更新通道。"><div className="min-w-56"><GithubAccount controller={c}/></div></SettingRow>
      <SettingRow title="自动更新" description={d.update.configured?'启动时自动检查正式版更新，更新后自动重启。':'仓库与签名公钥尚未填写，配置步骤见 docs/GitHub_and_Updates.md。'}><Badge variant="secondary">{d.update.configured?'已启用':'待配置'}</Badge></SettingRow>
      <SettingRow title="发布渠道" description="正式版跟随 GitHub Releases 的最新版本。"><Badge variant="secondary">正式版</Badge></SettingRow>
    </SettingsGroup>
    <SettingsGroup title="文档与反馈">
      <SettingRow title="源码仓库" description="代码、问题反馈与版本发布都集中在这里。"><a className="about-link" href="https://github.com" target="_blank" rel="noreferrer">GitHub<ExternalLink size={12}/></a></SettingRow>
      <SettingRow title="发布日志" description="每个版本的改动记录。"><a className="about-link" href="https://github.com" target="_blank" rel="noreferrer">Releases<ExternalLink size={12}/></a></SettingRow>
      <SettingRow title="帮助与反馈" description="使用问题、功能建议与缺陷报告。"><a className="about-link" href="https://github.com" target="_blank" rel="noreferrer">Issues<ExternalLink size={12}/></a></SettingRow>
    </SettingsGroup>
    <p className="text-xs leading-6 text-muted-foreground">侧边终端与扩展属于 P1 范围。当前版本聚焦 macOS 上的 Finder 附加底栏与文件处理。</p>
  </div>;
}
